<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ListOfKpiSeeder extends Seeder
{
    public function run()
    {
        //
        $data = [
            ['name' => 'sop/i complay & laporan gangguan boiler pltu shift a'],
            ['name' => 'sop/i complay & laporan gangguan boiler pltu shift b'],
            ['name' => 'sop/i complay & laporan gangguan boiler pltu shift c'],
            ['name' => 'sop/i complay & laporan gangguan boiler pltu shift d'],
            ['name' => 'sop/i complay & laporan gangguan turbin pltu shift a'],
            ['name' => 'sop/i complay & laporan gangguan turbin pltu shift b'],
            ['name' => 'sop/i complay & laporan gangguan turbin pltu shift c'],
            ['name' => 'sop/i complay & laporan gangguan turbin pltu shift d'],
            ['name' => 'sop/i complay & laporan gangguan alba pltu shift a'],
            ['name' => 'sop/i complay & laporan gangguan alba pltu shift b'],
            ['name' => 'sop/i complay & laporan gangguan alba pltu shift c'],
            ['name' => 'sop/i complay & laporan gangguan alba pltu shift d'],
            ['name' => 'maturity level shift meeting pltu shift a'],
            ['name' => 'maturity level shift meeting pltu shift b'],
            ['name' => 'maturity level shift meeting pltu shift c'],
            ['name' => 'maturity level shift meeting pltu shift d'],
            ['name' => 'entry data parameter operasi boiler pltu shift a'],
            ['name' => 'entry data parameter operasi boiler pltu shift b'],
            ['name' => 'entry data parameter operasi boiler pltu shift c'],
            ['name' => 'entry data parameter operasi boiler pltu shift d'],
            ['name' => 'entry data parameter operasi turbin pltu shift a'],
            ['name' => 'entry data parameter operasi turbin pltu shift b'],
            ['name' => 'entry data parameter operasi turbin pltu shift c'],
            ['name' => 'entry data parameter operasi turbin pltu shift d'],
            ['name' => 'entry data parameter operasi alba pltu shift a'],
            ['name' => 'entry data parameter operasi alba pltu shift b'],
            ['name' => 'entry data parameter operasi alba pltu shift c'],
            ['name' => 'entry data parameter operasi alba pltu shift d'],
            ['name' => 'house keeping operasi boiler pltu shift a'],
            ['name' => 'house keeping operasi boiler pltu shift b'],
            ['name' => 'house keeping operasi boiler pltu shift c'],
            ['name' => 'house keeping operasi boiler pltu shift d'],
            ['name' => 'house keeping operasi turbin pltu shift a'],
            ['name' => 'house keeping operasi turbin pltu shift b'],
            ['name' => 'house keeping operasi turbin pltu shift c'],
            ['name' => 'house keeping operasi turbin pltu shift d'],
            ['name' => 'house keeping operasi alba pltu shift a'],
            ['name' => 'house keeping operasi alba pltu shift b'],
            ['name' => 'house keeping operasi alba pltu shift c'],
            ['name' => 'house keeping operasi alba pltu shift d'],
            ['name' => 'patrol check boiler pltu shift a'],
            ['name' => 'patrol check boiler pltu shift b'],
            ['name' => 'patrol check boiler pltu shift c'],
            ['name' => 'patrol check boiler pltu shift d'],
            ['name' => 'patrol check turbin pltu shift a'],
            ['name' => 'patrol check turbin pltu shift b'],
            ['name' => 'patrol check turbin pltu shift c'],
            ['name' => 'patrol check turbin pltu shift d'],
            ['name' => 'patrol check alba pltu shift a'],
            ['name' => 'patrol check alba pltu shift b'],
            ['name' => 'patrol check alba pltu shift c'],
            ['name' => 'patrol check alba pltu shift d'],
            ['name' => 'first line maintenance boiler pltu shift a'],
            ['name' => 'first line maintenance boiler pltu shift b'],
            ['name' => 'first line maintenance boiler pltu shift c'],
            ['name' => 'first line maintenance boiler pltu shift d'],
            ['name' => 'first line maintenance turbin pltu shift a'],
            ['name' => 'first line maintenance turbin pltu shift b'],
            ['name' => 'first line maintenance turbin pltu shift c'],
            ['name' => 'first line maintenance turbin pltu shift d'],
            ['name' => 'first line maintenance alba pltu shift a'],
            ['name' => 'first line maintenance alba pltu shift b'],
            ['name' => 'first line maintenance alba pltu shift c'],
            ['name' => 'first line maintenance alba pltu shift d'],
            ['name' => 'kualitas ils/kk boiler pltu shift a'],
            ['name' => 'kualitas ils/kk boiler pltu shift b'],
            ['name' => 'kualitas ils/kk boiler pltu shift c'],
            ['name' => 'kualitas ils/kk boiler pltu shift d'],
            ['name' => 'kualitas ils/kk turbin pltu shift a'],
            ['name' => 'kualitas ils/kk turbin pltu shift b'],
            ['name' => 'kualitas ils/kk turbin pltu shift c'],
            ['name' => 'kualitas ils/kk turbin pltu shift d'],
            ['name' => 'kualitas ils/kk alba pltu shift a'],
            ['name' => 'kualitas ils/kk alba pltu shift b'],
            ['name' => 'kualitas ils/kk alba pltu shift c'],
            ['name' => 'kualitas ils/kk alba pltu shift d'],
            ['name' => 'review sop pltu shift a'],
            ['name' => 'review sop pltu shift b'],
            ['name' => 'review sop pltu shift c'],
            ['name' => 'review sop pltu shift d'],
            ['name' => 'sistem loto pltu shift a'],
            ['name' => 'sistem loto pltu shift b'],
            ['name' => 'sistem loto pltu shift c'],
            ['name' => 'sistem loto pltu shift d'],
            ['name' => 'komunikasi dengan dispatcher & pelaporan pltu shift a'],
            ['name' => 'komunikasi dengan dispatcher & pelaporan pltu shift b'],
            ['name' => 'komunikasi dengan dispatcher & pelaporan pltu shift c'],
            ['name' => 'komunikasi dengan dispatcher & pelaporan pltu shift d'],
            ['name' => 'warming up peralatan standby pltu shift a'],
            ['name' => 'warming up peralatan standby pltu shift b'],
            ['name' => 'warming up peralatan standby pltu shift c'],
            ['name' => 'warming up peralatan standby pltu shift d'],
        ];

        $this->db->table('list_of_kpi')->insertBatch($data);
    }
}

// $ php spark db:seed ListOfKpiSeeder
