<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ServiceRequestSeeder extends Seeder
{
    public function run()
    {
        //
        $data = [
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-06'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-07'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-07'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-07'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-10'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-11'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-12'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-13'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-13'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-14'),
            ],
            [
                'nomorSr' => '4324',
                'unit' => '#1',
                'area' => 'boiler',
                'namaPeralatan' => 'hpff',
                'kks' => '123ert45',
                'uraianGangguan1' => 'ada',
                'uraianGangguan2' => 'ada',
                'normalOperasi1' => 'n',
                'normalOperasi2' => 'n',
                'gejala1' => 'n',
                'gejala2' => 'n',
                'prioritas' => 'n',
                'akibatKerusakan1' => 'n',
                'akibatKerusakan2' => 'n',
                'kemungkinanDampak1' => 'n',
                'kemungkinanDampak2' => 'n',
                'tindakanSementara1' => 'n',
                'tindakanSementara2' => 'n',
                'tindakanSementara3' => 'n',
                'diinput_oleh' => '9617075fby',
                'tanggal' => date('Y-m-16'),
            ],
        ];

        $this->db->table('srcm')->insertBatch($data);
    }
}

// $ php spark db:seed ListOfKpiSeeder
